### PR TITLE
Translate into german

### PR DESCRIPTION
**Pull request by Talaren**
* Added first Version of Translation into German
* en.json with json formatter formatted for better compare with the translation file.

### CODE REVIEW

**Comment by Talaren** [comment]
@Sk1mble i hope all fine with this pull request?

**Comment by Sk1mble** [comment]
Hi, I'm a bit uncomfortable with merging this as-is because whatever you did to the english language json file it's showing all 5,000-odd lines as having changed and that makes it really difficult to see exactly what you did.

**Comment by Talaren** [comment]
@Sk1mble Ok i can understood you.
First i formatted the en.json File Notepad++ + JSON Viewer Format.
This commit: https://github.com/Sk1mble/fate-core-official/pull/6/commits/25d57b0d0659c5b076227a50ec5f48911d3d0e0e
then i added the deepl Translation and correct the error and parse all through a JSON parser.
Then i found a error the Copy was duplicated, i remove one Version
https://github.com/Sk1mble/fate-core-official/pull/6/commits/a1eee2c81633c4ee4ae5b7062503dae083e171f1
this was the only change on the en.json

**Review by Sk1mble — APPROVED** [review]

**Comment by Sk1mble** [comment]
Merge German translation.

**Pull request merged**
